import type { CustomerCreditEntry, CreditReason } from '@/types/crm'

// Customer-credit helpers. PostgREST returns numeric columns as strings, so
// every read is coerced with Number(...) here. The authoritative balance and
// all mutations live in SQL (crm_customer_credit + the crm_* RPCs) — these
// helpers only derive display figures from already-fetched ledger rows.

/** Sum of a customer's ledger entries. Floored at 0 to match the DB guard. */
export function creditBalance(entries: Pick<CustomerCreditEntry, 'amount'>[]): number {
  const total = entries.reduce((sum, e) => sum + (Number(e.amount) || 0), 0)
  return Math.max(0, total)
}

/** Overpayment credit generated by a specific order (positive), if any. */
export function overpaymentForOrder(
  entries: Pick<CustomerCreditEntry, 'order_id' | 'reason' | 'amount'>[],
  orderId: string,
): number {
  return entries
    .filter(e => e.order_id === orderId && e.reason === 'order_overpayment')
    .reduce((sum, e) => sum + (Number(e.amount) || 0), 0)
}

/** Credit applied to a specific order (returned positive), if any. */
export function appliedCreditForOrder(
  entries: Pick<CustomerCreditEntry, 'order_id' | 'reason' | 'amount'>[],
  orderId: string,
): number {
  return entries
    .filter(e => e.order_id === orderId && e.reason === 'applied_to_order')
    .reduce((sum, e) => sum - (Number(e.amount) || 0), 0)
}

/** Human-readable label for a ledger entry's reason. */
export const CREDIT_REASON_LABELS: Record<CreditReason, string> = {
  order_overpayment: 'Overpayment',
  applied_to_order: 'Applied to order',
  manual_adjustment: 'Adjustment',
}
