import { LogbookStage } from '@/types/logbook'

export const LOGBOOK_STAGES: LogbookStage[] = [
  {
    id: 'stage_2',
    name: 'Stage 2 - Applied Skills',
    categories: [
      {
        id: 's2_nh',
        name: 'Honeybee Natural History',
        skills: [
          { id: 's2_nh_01', description: 'Identify the three castes of honeybee' },
          { id: 's2_nh_02', description: 'Identify drone, worker and queen cells on a frame' },
          { id: 's2_nh_03', description: 'Identify eggs, larvae (unsealed brood) and pupae (sealed brood)' },
          { id: 's2_nh_04', description: 'Identify the queen on a frame' },
          { id: 's2_nh_05', description: 'Identify stored pollen' },
          { id: 's2_nh_06', description: 'Identify sealed and unsealed honey stores' },
          { id: 's2_nh_07', description: 'Identify propolis in the hive' },
          { id: 's2_nh_08', description: 'Identify fresh wax in the hive' },
          { id: 's2_nh_09', description: 'Demonstrate awareness of the life cycle of the honeybee' },
          { id: 's2_nh_10', description: 'Demonstrate awareness of the role of pheromones in the colony' },
          { id: 's2_nh_11', description: 'Demonstrate awareness of the swarming impulse' },
          { id: 's2_nh_12', description: 'Identify signs that a colony is preparing to swarm' },
          { id: 's2_nh_13', description: 'Demonstrate awareness of how bees communicate' },
          { id: 's2_nh_14', description: 'Demonstrate awareness of the annual cycle of a honeybee colony' },
          { id: 's2_nh_15', description: 'Demonstrate awareness of the mating process of the queen' },
          { id: 's2_nh_16', description: 'Demonstrate awareness of the role of drones in the colony' },
        ],
      },
      {
        id: 's2_hm',
        name: 'Honeybee Management',
        skills: [
          { id: 's2_hm_01', description: 'Open and close a hive correctly' },
          { id: 's2_hm_02', description: 'Light and use a smoker effectively' },
          { id: 's2_hm_03', description: 'Handle frames correctly during an inspection' },
          { id: 's2_hm_04', description: 'Assess the strength of a colony' },
          { id: 's2_hm_05', description: 'Assess the temperament of a colony' },
          { id: 's2_hm_06', description: 'Check for signs of queenlessness' },
          { id: 's2_hm_07', description: 'Check for signs of a laying worker' },
          { id: 's2_hm_08', description: 'Mark a queen' },
          { id: 's2_hm_09', description: 'Clip a queen' },
          { id: 's2_hm_10', description: 'Demonstrate a method of swarm prevention' },
          { id: 's2_hm_11', description: 'Demonstrate a method of swarm control' },
          { id: 's2_hm_12', description: 'Unite two colonies' },
          { id: 's2_hm_13', description: 'Prepare a colony for winter' },
        ],
      },
      {
        id: 's2_pd',
        name: 'Honeybee Pests and Diseases',
        skills: [
          { id: 's2_pd_01', description: 'Demonstrate awareness of the signs of American Foulbrood (AFB)' },
          { id: 's2_pd_02', description: 'Demonstrate awareness of the signs of European Foulbrood (EFB)' },
          { id: 's2_pd_03', description: 'Carry out the ropiness test for AFB' },
          { id: 's2_pd_04', description: 'Demonstrate awareness of the signs of chalkbrood' },
          { id: 's2_pd_05', description: 'Demonstrate awareness of the signs of sacbrood' },
          { id: 's2_pd_06', description: 'Demonstrate awareness of Nosema' },
          { id: 's2_pd_07', description: 'Demonstrate awareness of Acarine' },
          { id: 's2_pd_08', description: 'Demonstrate awareness of the Varroa mite life cycle' },
          { id: 's2_pd_09', description: 'Carry out a Varroa mite count (sugar roll or alcohol wash)' },
          { id: 's2_pd_10', description: 'Carry out a Varroa mite count (natural mite drop)' },
          { id: 's2_pd_11', description: 'Apply a Varroa treatment correctly' },
          { id: 's2_pd_12', description: 'Demonstrate awareness of Integrated Pest Management (IPM)' },
          { id: 's2_pd_13', description: 'Demonstrate awareness of the Small Hive Beetle' },
          { id: 's2_pd_14', description: 'Demonstrate awareness of the Asian Hornet' },
          { id: 's2_pd_15', description: 'Demonstrate awareness of wax moth damage' },
          { id: 's2_pd_16', description: 'Demonstrate awareness of the legal requirements for notifiable diseases' },
          { id: 's2_pd_17', description: 'Demonstrate awareness of good apiary hygiene practices' },
        ],
      },
      {
        id: 's2_pf',
        name: 'Honeybee Products and Forage',
        skills: [
          { id: 's2_pf_01', description: 'Identify three major honeybee forage plants in your area' },
          { id: 's2_pf_02', description: 'Demonstrate awareness of the importance of forage availability' },
          { id: 's2_pf_03', description: 'Harvest honey from a hive' },
          { id: 's2_pf_04', description: 'Extract and jar honey correctly' },
          { id: 's2_pf_05', description: 'Demonstrate awareness of beeswax processing' },
        ],
      },
      {
        id: 's2_mc',
        name: 'Manipulation of Honeybee Colonies',
        skills: [
          { id: 's2_mc_01', description: 'Make up a nucleus colony' },
          { id: 's2_mc_02', description: 'Introduce a new queen to a colony' },
          { id: 's2_mc_03', description: 'Requeen a colony' },
          { id: 's2_mc_04', description: 'Feed a colony with sugar syrup' },
          { id: 's2_mc_05', description: 'Feed a colony with fondant' },
          { id: 's2_mc_06', description: 'Add a super to a hive' },
          { id: 's2_mc_07', description: 'Remove a super from a hive' },
          { id: 's2_mc_08', description: 'Use a queen excluder correctly' },
          { id: 's2_mc_09', description: 'Move a hive to a new location' },
          { id: 's2_mc_10', description: 'Carry out a Bailey comb change' },
          { id: 's2_mc_11', description: 'Carry out a shook swarm' },
          { id: 's2_mc_12', description: 'Carry out a Pagden artificial swarm' },
          { id: 's2_mc_13', description: 'Demonstrate awareness of drone management' },
          { id: 's2_mc_14', description: 'Demonstrate awareness of the importance of record keeping' },
          { id: 's2_mc_15', description: 'Carry out a full hive inspection and complete a record' },
        ],
      },
      {
        id: 's2_eq',
        name: 'Equipment',
        skills: [
          { id: 's2_eq_01', description: 'Assemble a frame correctly' },
          { id: 's2_eq_02', description: 'Fit foundation into a frame' },
          { id: 's2_eq_03', description: 'Demonstrate knowledge of hive components' },
          { id: 's2_eq_04', description: 'Demonstrate awareness of different hive types' },
          { id: 's2_eq_05', description: 'Clean and sterilise hive equipment' },
          { id: 's2_eq_06', description: 'Demonstrate correct use of personal protective equipment' },
          { id: 's2_eq_07', description: 'Demonstrate awareness of safe storage of equipment and chemicals' },
        ],
      },
      {
        id: 's2_st',
        name: 'Stings',
        skills: [
          { id: 's2_st_01', description: 'Demonstrate correct removal of a sting' },
          { id: 's2_st_02', description: 'Demonstrate awareness of anaphylaxis and appropriate response' },
        ],
      },
    ],
  },
  {
    id: 'stage_3',
    name: 'Stage 3 - Applied Skills',
    categories: [
      {
        id: 's3_nh',
        name: 'Natural History',
        skills: [
          { id: 's3_nh_01', description: 'Describe and relate to practical beekeeping the main external features of the three castes' },
          { id: 's3_nh_02', description: 'Describe and relate to practical beekeeping the function of the hypopharyngeal, Nasonov and wax glands' },
          { id: 's3_nh_03', description: 'Describe and relate to practical beekeeping queen substance and how it affects queen cell production' },
          { id: 's3_nh_04', description: 'Describe and relate to practical beekeeping the factors in brood rearing which result in workers, queens and drones' },
          { id: 's3_nh_05', description: 'Describe and relate to practical beekeeping the mating of drones with queens' },
          { id: 's3_nh_06', description: 'Describe and relate to practical beekeeping the development of brood of each caste from egg to emerging adult' },
          { id: 's3_nh_07', description: 'Describe and relate to practical beekeeping honeybee nutritional requirements and their main sources' },
          { id: 's3_nh_08', description: 'Describe and relate to practical beekeeping the signs, causes and treatment of drone laying workers' },
          { id: 's3_nh_09', description: 'Describe and relate to practical beekeeping how hive population varies by season' },
          { id: 's3_nh_10', description: 'Describe and relate to practical beekeeping honeybee survival behaviour in winter' },
          { id: 's3_nh_11', description: 'Describe and relate to practical beekeeping the effect of weather on a colony and its foraging behaviour' },
          { id: 's3_nh_12', description: 'Outline and relate to practical beekeeping the tasks done by a worker honeybee during its life cycle' },
          { id: 's3_nh_13', description: 'Describe and relate to practical beekeeping the difference in tasks done by summer and winter adapted worker honeybees' },
          { id: 's3_nh_14', description: 'Outline and relate to practical beekeeping food sharing in the colony' },
          { id: 's3_nh_15', description: 'Outline and relate to practical beekeeping the production and use of wax in the colony' },
          { id: 's3_nh_16', description: 'Outline and relate to practical beekeeping the collection of propolis and its use in the colony' },
          { id: 's3_nh_17', description: 'Describe the appearance of swarm, supersedure and emergency queen cells and what to do in each case' },
          { id: 's3_nh_18', description: 'Describe and relate to practical beekeeping the use of alarm pheromones by honey bees' },
        ],
      },
      {
        id: 's3_hf',
        name: 'Honeybee Forage',
        skills: [
          { id: 's3_hf_01', description: 'List the forage plants of local importance and their flowering periods' },
          { id: 's3_hf_02', description: 'Outline and relate to practical beekeeping the collection of nectar and its conversion into honey for storage in sealed comb' },
          { id: 's3_hf_03', description: 'Outline and relate to practical beekeeping the collection of pollen and how it is carried to the colony and used' },
          { id: 's3_hf_04', description: 'Outline and relate to practical beekeeping the collection of water and its use in the colony' },
          { id: 's3_hf_05', description: 'Outline and relate to practical beekeeping the collection of propolis and its use in the colony' },
        ],
      },
      {
        id: 's3_me',
        name: 'Manipulations and Equipment',
        skills: [
          { id: 's3_me_01', description: 'Discuss the principles and methods of uniting honeybee colonies' },
          { id: 's3_me_02', description: 'Demonstrate making up a nucleus for swarm control, queen rearing and increase' },
          { id: 's3_me_03', description: 'Demonstrate and explain a swarm control method of candidate\u2019s choice' },
          { id: 's3_me_04', description: 'Explain procedure for preserving hives' },
          { id: 's3_me_05', description: 'Explain procedure for fumigating comb and equipment' },
          { id: 's3_me_06', description: 'Explain procedure for preventing wax moth damage' },
          { id: 's3_me_07', description: 'Explain procedure for using predator guards' },
          { id: 's3_me_08', description: 'Explain procedure for storing combs' },
        ],
      },
      {
        id: 's3_am',
        name: 'Apiary and Honeybee Management',
        skills: [
          { id: 's3_am_01', description: 'Demonstrate preparing a colony for moving to another apiary' },
          { id: 's3_am_02', description: 'Explain procedure for moving a colony within an apiary and its possible problems' },
          { id: 's3_am_03', description: 'Explain procedure for moving a colony further than flying distance and its possible problems' },
          { id: 's3_am_04', description: 'Present outline plans with dates for swarm control' },
          { id: 's3_am_05', description: 'Present outline plans for equipment purchase and repairs' },
          { id: 's3_am_06', description: 'Present outline plans with dates for queen replacement' },
          { id: 's3_am_07', description: 'Present outline contingency plans for re-siting colonies' },
        ],
      },
      {
        id: 's3_pb',
        name: 'Practical Beekeeping',
        skills: [
          { id: 's3_pb_01', description: 'Discuss and explain the progress of colonies based on their hive records' },
          { id: 's3_pb_02', description: 'Discuss and explain how honey production influences apiary procedures' },
          { id: 's3_pb_03', description: 'Discuss and explain the procedures for adding supers to colonies' },
          { id: 's3_pb_04', description: 'Discuss and explain how local conditions affect the choice of hives, equipment and top or bottom bee space' },
          { id: 's3_pb_05', description: 'Discuss and explain the dangers of robbing and how to prevent or stop it' },
          { id: 's3_pb_06', description: 'Discuss the drifting of honeybees, the dangers caused and apiary layouts to reduce it' },
          { id: 's3_pb_07', description: 'Discuss and explain how honeybees might become a nuisance to people or livestock' },
          { id: 's3_pb_08', description: 'Discuss and explain how to store super combs and combat wax moths' },
          { id: 's3_pb_09', description: 'Discuss and explain how and why to feed sugar syrup, candy, pollen and pollen substitute to bees' },
          { id: 's3_pb_10', description: 'Discuss and explain how and when to prepare colonies for winter' },
          { id: 's3_pb_11', description: 'Discuss and explain how to deal with a vicious bee colony' },
        ],
      },
      {
        id: 's3_hr',
        name: 'Hive Records',
        skills: [
          { id: 's3_hr_01', description: 'Present records of every hive inspection for 3 continuous years to date' },
          { id: 's3_hr_02', description: 'Show in hive records queen status from none to present to laying' },
          { id: 's3_hr_03', description: 'Show in hive records presence of queen cells or cups' },
          { id: 's3_hr_04', description: 'Show in hive records temper of the colony from very docile to unworkable' },
          { id: 's3_hr_05', description: 'Show in hive records the degree of disease and probable disease seen' },
          { id: 's3_hr_06', description: 'Show in hive records the brood size and pattern' },
          { id: 's3_hr_07', description: 'Show in hive records the quantities of stores available including pollen' },
          { id: 's3_hr_08', description: 'Show in hive records space available for colony expansion' },
          { id: 's3_hr_09', description: 'Show in hive records feeding dates, quantities and types of feed given' },
          { id: 's3_hr_10', description: 'Show in hive records frames and supers added or removed' },
          { id: 's3_hr_11', description: 'Show in hive records all queen rearing activities' },
          { id: 's3_hr_12', description: 'Show in hive records swarm control actions' },
          { id: 's3_hr_13', description: 'Show in hive records all disease control activities including the use of medicines' },
          { id: 's3_hr_14', description: 'Show in hive records details of each colony\u2019s origin' },
          { id: 's3_hr_15', description: 'Show in hive records the apiary layout and the location and number of each hive' },
        ],
      },
      {
        id: 's3_sc',
        name: 'Swarming, Swarm Control and Effects',
        skills: [
          { id: 's3_sc_01', description: 'Explain the factors that may encourage swarming' },
          { id: 's3_sc_02', description: 'Describe the indications that a colony is preparing to swarm' },
          { id: 's3_sc_03', description: 'Describe the economic and social effects of swarming' },
          { id: 's3_sc_04', description: 'Describe the procedures used to control swarming' },
          { id: 's3_sc_05', description: 'Demonstrate procedures for creating an artificial swarm other than using a nucleus' },
        ],
      },
      {
        id: 's3_hp',
        name: 'Honeybee Products',
        skills: [
          { id: 's3_hp_01', description: 'Describe beeswax recovery and the equipment used' },
          { id: 's3_hp_02', description: 'Describe the equipment used to refine beeswax suitable for retail sale' },
          { id: 's3_hp_03', description: 'Describe how to prepare honeybees to forage on a local or distant single crop' },
          { id: 's3_hp_04', description: 'Describe the normal apiary equipment for honey production and its use' },
          { id: 's3_hp_05', description: 'Explain the use of the various devices for clearing honeybees from supers' },
          { id: 's3_hp_06', description: 'Present samples of own honey prepared for the table and for sale' },
          { id: 's3_hp_07', description: 'Explain the preparation of good quality liquid, soft set and granulated honey' },
          { id: 's3_hp_08', description: 'Explain the production methods for comb honey' },
          { id: 's3_hp_09', description: 'Describe the methods and equipment for extracting honey from comb' },
          { id: 's3_hp_10', description: 'Describe storage arrangements and conditions for processed honey' },
          { id: 's3_hp_11', description: 'Describe Food Safety Authority of Ireland and other standards that apply to honey production and processing' },
        ],
      },
      {
        id: 's3_sb',
        name: 'Selection and Breeding of Honeybees',
        skills: [
          { id: 's3_sb_01', description: 'Describe and relate to practical beekeeping the different races of honeybees, their hybrids and their characteristics' },
          { id: 's3_sb_02', description: 'Describe the advantages of marking and clipping queens' },
          { id: 's3_sb_03', description: 'Demonstrate marking and clipping a queen (or a drone if a substitute is appropriate)' },
          { id: 's3_sb_04', description: 'Demonstrate and explain a queen rearing method of candidate\u2019s choice' },
          { id: 's3_sb_05', description: 'Explain the reasons for selecting a particular queen for breeding' },
          { id: 's3_sb_06', description: 'Review the age of existing queens in an apiary and show plans with dates for their replacement' },
          { id: 's3_sb_07', description: 'Describe how queens are replaced' },
          { id: 's3_sb_08', description: 'Describe a plan for a successfully mated queen' },
          { id: 's3_sb_09', description: 'Describe the procedure for introducing a queen into a colony' },
        ],
      },
      {
        id: 's3_hh',
        name: 'Honeybee Health',
        skills: [
          { id: 's3_hh_01', description: 'Explain the importance of good apiary hygiene to honeybee health' },
          { id: 's3_hh_02', description: 'Explain procedures for general apiary hygiene' },
          { id: 's3_hh_03', description: 'Demonstrate the inspection of a brood comb for brood diseases' },
          { id: 's3_hh_04', description: 'Demonstrate taking and sending a sample of adult bees for disease diagnosis' },
          { id: 's3_hh_05', description: 'Present lab report on previous sample of adult bees' },
          { id: 's3_hh_06', description: 'Demonstrate how to monitor and control Varroa to non-damaging levels through the year' },
          { id: 's3_hh_07', description: 'Demonstrate the use of Varroa control equipment in the apiary' },
          { id: 's3_hh_08', description: 'Examine a brood chamber and floor for Varroa' },
          { id: 's3_hh_09', description: 'Demonstrate the use of drone comb for trapping Varroa mites' },
          { id: 's3_hh_10', description: 'Demonstrate how to renew comb and explain why' },
          { id: 's3_hh_11', description: 'Explain why a colony might need to be killed and how it should be done' },
          { id: 's3_hh_12', description: 'Describe the routine methods of checking for disease in a honeybee colony' },
          { id: 's3_hh_13', description: 'Describe the appearance of healthy brood re. larvae, brood pattern and cell cappings' },
          { id: 's3_hh_14', description: 'List methods of avoiding or reducing infectious disease transmission, and explain how to apply them' },
          { id: 's3_hh_15', description: 'Describe the signs of American Foulbrood and its effects on a colony' },
          { id: 's3_hh_16', description: 'Describe the signs of European Foulbrood and its effects on a colony' },
          { id: 's3_hh_17', description: 'Describe how to comply with statutory requirements if a brood disease is suspected' },
          { id: 's3_hh_18', description: 'Use an effective method to monitor and control Varroa' },
          { id: 's3_hh_19', description: 'Describe the impact of virus damage due to Varroa infestation' },
          { id: 's3_hh_20', description: 'Describe how Varroa re-infestation affects the management and timing of Varroa control' },
          { id: 's3_hh_21', description: 'Describe the effects of Nosema disease on a honeybee colony, its diagnosis and control' },
          { id: 's3_hh_22', description: 'Describe the effects of Acarine on a honeybee colony, its detection and control' },
          { id: 's3_hh_23', description: 'Describe the appearance and effects of Chalk Brood and Sac Brood on a colony, and their control' },
          { id: 's3_hh_24', description: 'Describe Chilled Brood and Bald Brood and their possible effects on a colony' },
          { id: 's3_hh_25', description: 'Outline the current regulations and statutory requirements in respect of bee pests and diseases' },
          { id: 's3_hh_26', description: 'Outline and relate to practical beekeeping the concept of Integrated Pest Management' },
          { id: 's3_hh_27', description: 'List the potential new pest and disease threats to beekeeping in Ireland' },
        ],
      },
    ],
  },
  {
    id: 'stage_4',
    name: 'Stage 4 - Applied Skills',
    categories: [
      {
        id: 's4_nh',
        name: 'Natural History',
        skills: [
          { id: 's4_nh_01', description: 'Describe the production of the sexes and the three castes' },
          { id: 's4_nh_02', description: 'Describe and relate to practical beekeeping the adult life expectancy of the three castes' },
          { id: 's4_nh_03', description: 'Describe the production and appearance of swarm, supersedure and emergency queen cells and the factors that may give rise to each' },
          { id: 's4_nh_04', description: 'Discuss the mating behaviour of honeybee queens and drones including the roles of pheromones and drone congregation areas' },
          { id: 's4_nh_05', description: 'Describe the signs in a colony, causes and treatment of drone laying queens and laying workers' },
          { id: 's4_nh_06', description: 'Describe the signs of queenlessness and how it may be confirmed and dealt with' },
        ],
      },
      {
        id: 's4_hb',
        name: 'Honeybee Behaviour',
        skills: [
          { id: 's4_hb_01', description: 'Describe the functions and behaviour of worker honeybees throughout their life including types and duration of tasks done and how they vary due to seasonal changes and the state of the colony' },
          { id: 's4_hb_02', description: 'Describe and relate to practical beekeeping the number of eggs laid by a queen and the factors influencing it through the year' },
          { id: 's4_hb_03', description: 'Describe how honeybees communicate including food sharing, dancing, scenting and vibration' },
          { id: 's4_hb_04', description: 'Describe honeybee defensive behaviour' },
          { id: 's4_hb_05', description: 'Explain the interrelationship of nectar, honey and water in the honeybee colony' },
          { id: 's4_hb_06', description: 'Discuss the conditions leading to supersedure' },
          { id: 's4_hb_07', description: 'Describe the behaviour and survival requirements for honeybee swarms' },
          { id: 's4_hb_08', description: 'Describe how honeybees produce beeswax, initiate comb building and construct comb' },
          { id: 's4_hb_09', description: 'Describe the behaviour and survival requirements of a honeybee colony in winter' },
        ],
      },
      {
        id: 's4_fp',
        name: 'Honeybee Forage, Plants and Pollination',
        skills: [
          { id: 's4_fp_01', description: 'Explain the value of honey and pollen to honeybees' },
          { id: 's4_fp_02', description: 'Describe foraging honeybee behaviour and work methods in the field, including orientation' },
          { id: 's4_fp_03', description: 'Discuss the species and flowering times of plants important to honeybees in Ireland and particularly those in the candidate\u2019s own locality' },
          { id: 's4_fp_04', description: 'Discuss the influence of weather conditions and plant species on nectar secretion and composition' },
          { id: 's4_fp_05', description: 'Outline the problems in extracting such honeys as Brassica (rape, mustard etc.), ivy and heather' },
          { id: 's4_fp_06', description: 'Describe the origin and appearance of honeydew and its effect upon the resulting honey' },
          { id: 's4_fp_07', description: 'Discuss the pollination of flowering plants and the use of honeybee colonies in the pollination of seed and fruit crops' },
          { id: 's4_fp_08', description: 'Discuss the floral sources of undesirable nectar and its effect on honeybees and the honey produced' },
        ],
      },
      {
        id: 's4_am',
        name: 'Apiary and Honeybee Management',
        skills: [
          { id: 's4_am_01', description: 'Describe the use of honeybees as pollinators in fruit and other crops and arrangements to be made with the farmer/grower' },
          { id: 's4_am_02', description: 'Describe the management of colonies for oilseed rape and ling heather honey production' },
          { id: 's4_am_03', description: 'Define \u2018bee space\u2019' },
          { id: 's4_am_04', description: 'Discuss the influence of bee space on beekeeping equipment design' },
          { id: 's4_am_05', description: 'Discuss the various patterns of hive used in Ireland' },
          { id: 's4_am_06', description: 'Discuss the various types of frame used in Ireland' },
          { id: 's4_am_07', description: 'Discuss the use and home production of wax foundation' },
          { id: 's4_am_08', description: 'Discuss the methods of fitting frames with wax foundation, including wiring and embedding' },
          { id: 's4_am_09', description: 'Discuss the various methods of spacing frames in hives' },
          { id: 's4_am_10', description: 'Discuss the usual dimensions of frame spacings in hives, and the advantages and disadvantages of varying them' },
          { id: 's4_am_11', description: 'Discuss how to begin beekeeping, including acquisition of bees, sources and costs of equipment, and any necessary precautions' },
          { id: 's4_am_12', description: 'Discuss the criteria used in selecting apiary sites' },
          { id: 's4_am_13', description: 'Discuss the factors to consider when setting up colonies in apiaries' },
          { id: 's4_am_14', description: 'Discuss and explain drifting, its control and when it can be used to divert bees to other colonies' },
          { id: 's4_am_15', description: 'Discuss the year\u2019s work in the apiary and how it depends on the annual colony cycle and local forage timing' },
          { id: 's4_am_16', description: 'Discuss honeybee feeding including feeder types, amounts fed, types of food and timing' },
          { id: 's4_am_17', description: 'Discuss the preparation and use of pollen substitutes and supplements' },
          { id: 's4_am_18', description: 'Discuss the supering of honeybee colonies and how it relates to swarm prevention' },
          { id: 's4_am_19', description: 'Discuss the use of queen excluders and the types in common use' },
          { id: 's4_am_20', description: 'Discuss the various swarm prevention and control methods' },
          { id: 's4_am_21', description: 'Discuss the methods of taking and hiving honeybee swarms' },
          { id: 's4_am_22', description: 'Discuss the methods of making nuclei and their various uses' },
          { id: 's4_am_23', description: 'Discuss how swarms and nuclei can be built up into productive colonies' },
          { id: 's4_am_24', description: 'Demonstrate uniting two colonies and explain the precautions needed' },
          { id: 's4_am_25', description: 'Demonstrate Shook Swarm technique for disease control' },
          { id: 's4_am_26', description: 'Demonstrate changing all the frames in a strong colony, keeping the existing brood' },
          { id: 's4_am_27', description: 'Demonstrate Bailey Frame Change in a weak colony for disease control' },
          { id: 's4_am_28', description: 'Discuss the effects of time of year, weather conditions and strain of honeybee on the difficulty of queen introduction' },
          { id: 's4_am_29', description: 'Discuss the spring management of honeybees' },
          { id: 's4_am_30', description: 'Discuss the effects of oilseed rape on colony management, carryover of honey in combs and colony wintering' },
          { id: 's4_am_31', description: 'Discuss the assessment of a colony\u2019s quality for honey production' },
          { id: 's4_am_32', description: 'Discuss how the variable temperament of honeybees influences management and public relations' },
          { id: 's4_am_33', description: 'Discuss the methods, value and risks of marking and clipping queens' },
          { id: 's4_am_34', description: 'Discuss the summer management of honeybee colonies' },
          { id: 's4_am_35', description: 'Discuss how management changes with different locations, weather conditions and timing of forage plant flowering' },
          { id: 's4_am_36', description: 'Discuss the management of colonies to produce sections, comb and cut comb honey' },
          { id: 's4_am_37', description: 'Discuss the methods, difficulties and dangers of moving colonies' },
          { id: 's4_am_38', description: 'Discuss the management of colonies for migratory honey production and pollination services' },
          { id: 's4_am_39', description: 'Discuss the methods of clearing bees from supers' },
          { id: 's4_am_40', description: 'Discuss the principles and methods of preparing colonies for winter' },
          { id: 's4_am_41', description: 'Discuss the use of mouse and predator guards and the damage these pests can cause' },
          { id: 's4_am_42', description: 'Discuss the damage caused by the two species of wax moth' },
          { id: 's4_am_43', description: 'Discuss the methods of storing comb to prevent wax moth damage' },
          { id: 's4_am_44', description: 'Discuss the methods of fumigating comb and equipment and the safety precautions needed' },
          { id: 's4_am_45', description: 'Discuss the general maintenance and preservation of beehives' },
          { id: 's4_am_46', description: 'Discuss the uses, setting up and management through the year of observation hives' },
        ],
      },
      {
        id: 's4_ae',
        name: 'Apiary and Equipment',
        skills: [
          { id: 's4_ae_01', description: 'Present records of every hive inspection for 5 continuous years to date' },
          { id: 's4_ae_02', description: 'Present candidate\u2019s apiary or apiaries for inspection' },
          { id: 's4_ae_03', description: 'Present spare equipment for inspection' },
          { id: 's4_ae_04', description: 'Present combs not in use for inspection and demonstrate methods and place of storage' },
          { id: 's4_ae_05', description: 'Show how combs are stored to keep them free of vermin, dust, dirt, and absorption of contaminants' },
          { id: 's4_ae_06', description: 'Show how wax foundation is stored to keep it fresh and free of contaminants' },
          { id: 's4_ae_07', description: 'Present for inspection the equipment used for the recovery of beeswax' },
          { id: 's4_ae_08', description: 'Present samples of candidate\u2019s honey labelled ready for sale' },
          { id: 's4_ae_09', description: 'Present samples of candidate\u2019s beeswax ready for sale' },
        ],
      },
      {
        id: 's4_pb',
        name: 'Practical Beekeeping',
        skills: [
          { id: 's4_pb_01', description: 'Perform any manipulation of honeybee colonies requested by the assessor' },
          { id: 's4_pb_02', description: 'Use any of candidate\u2019s equipment requested by the assessor' },
          { id: 's4_pb_03', description: 'Describe the progress of each colony during the current season' },
          { id: 's4_pb_04', description: 'Describe the origin and age of the queen in each colony' },
          { id: 's4_pb_05', description: 'Discuss any disease present in the colonies and what action is being taken to deal with it' },
        ],
      },
      {
        id: 's4_pp',
        name: 'Honeybee Products and Processing',
        skills: [
          { id: 's4_pp_01', description: 'Describe properties of honey including composition, specific gravity, refractive index, viscosity, hygroscopicity and reactions to heat and ageing' },
          { id: 's4_pp_02', description: 'Describe the main statutory requirements for honey composition, handling, preparation for sale, weight of honey packs and labelling' },
          { id: 's4_pp_03', description: 'Describe methods of uncapping honeycombs and separating the honey from the cappings' },
          { id: 's4_pp_04', description: 'Describe the methods of extracting from the combs and bottling flower and ling heather honey, and the equipment used' },
          { id: 's4_pp_05', description: 'Describe the methods of straining and settling honey after extraction' },
          { id: 's4_pp_06', description: 'Discuss the granulation of honey and the factors affecting its speed, crystal size and final texture' },
          { id: 's4_pp_07', description: 'Describe the preparation of sections, cut comb and chunk honey for sale' },
          { id: 's4_pp_08', description: 'Describe the problems of high water content, frosting, fermentation and coarse granulation of honey, and how to avoid and remedy them' },
          { id: 's4_pp_09', description: 'Discuss the methods of measuring the water content of honey' },
          { id: 's4_pp_10', description: 'Describe the methods of recovering beeswax' },
          { id: 's4_pp_11', description: 'Describe the uses of beeswax' },
          { id: 's4_pp_12', description: 'Describe other hive products including pollen, royal jelly and propolis, and their uses' },
          { id: 's4_pp_13', description: 'Describe the preparation of honeybee products for a honey show' },
          { id: 's4_pp_14', description: 'Present extracting and honey handling equipment for inspection' },
          { id: 's4_pp_15', description: 'Demonstrate that the place where honey is extracted and handled complies with the current legal requirements for food processing and packing' },
          { id: 's4_pp_16', description: 'Explain the preparation of a location for honey processing' },
          { id: 's4_pp_17', description: 'Have vermin control in operation' },
          { id: 's4_pp_18', description: 'Demonstrate that water used for processing equipment is of potable quality' },
          { id: 's4_pp_19', description: 'Show what procedures are used to prepare jars for bottling' },
          { id: 's4_pp_20', description: 'Show how the cleaned extractor, settling tanks, buckets and associated equipment are stored when processing is complete' },
        ],
      },
      {
        id: 's4_sb',
        name: 'Selection and Breeding of Honeybees',
        skills: [
          { id: 's4_sb_01', description: 'Discuss the criteria used to select breeder queens and drones' },
          { id: 's4_sb_02', description: 'Present records of queen rearing and assessment of queens and their progeny' },
          { id: 's4_sb_03', description: 'Present for inspection the equipment used for queen rearing' },
          { id: 's4_sb_04', description: 'Discuss the different methods of queen rearing suitable for beekeepers with five to ten colonies and for larger scale queen rearing operations' },
          { id: 's4_sb_05', description: 'Outline a method of instrumental insemination and assess the role it could play in honeybee breeding' },
          { id: 's4_sb_06', description: 'Discuss candidate\u2019s own methods of selective queen rearing' },
          { id: 's4_sb_07', description: 'Discuss the various methods of queen introduction, their underlying principles, the precautions needed and any difficulties in relation to different strains of bee and colony condition' },
          { id: 's4_sb_08', description: 'Discuss the setting up of mating nuclei and any precautions needed' },
          { id: 's4_sb_09', description: 'Discuss the genetic basis of sex determination and parthenogenesis in honeybees' },
        ],
      },
      {
        id: 's4_hh',
        name: 'Honeybee Health',
        skills: [
          { id: 's4_hh_01', description: 'Explain the role of good apiary hygiene and best hygiene practices with personal and apiary equipment' },
          { id: 's4_hh_02', description: 'Describe the Irish statutory requirements for dealing with honeybee diseases and their implementation' },
          { id: 's4_hh_03', description: 'Discuss American Foul Brood (AFB) and European Foul Brood (EFB), their development within a colony and how they are spread between colonies' },
          { id: 's4_hh_04', description: 'Describe the signs and diagnosis of American Foul Brood (AFB) and European Foul Brood (EFB)' },
          { id: 's4_hh_05', description: 'Describe the treatment of American Foul Brood (AFB) and European Foul Brood (EFB) including methods of destroying colonies and sterilising equipment' },
          { id: 's4_hh_06', description: 'Discuss Nosema, its development within a colony and how it is spread between colonies' },
          { id: 's4_hh_07', description: 'Discuss the effects of viruses on honeybees and any associations with other bee diseases' },
          { id: 's4_hh_08', description: 'Discuss chalk, sac, chilled, bald, stone and neglected drone brood, their signs and causes and any recommended treatments' },
          { id: 's4_hh_09', description: 'Describe the signs and causes of all adult bee diseases found in Ireland and any methods of treating them' },
          { id: 's4_hh_10', description: 'Describe the life cycle and natural history of Varroa mites, their development within the honeybee colony and their spread to other colonies' },
          { id: 's4_hh_11', description: 'Describe how to recognise the signs of Varroa mite infestation' },
          { id: 's4_hh_12', description: 'Describe the currently advised monitoring, detection and treatment methods for Varroa mites' },
          { id: 's4_hh_13', description: 'Discuss the consequences of colony treatment for Varroa mites' },
          { id: 's4_hh_14', description: 'Describe the life cycle and natural history of Acarine mites, their development within the honeybee colony and their spread to other colonies' },
          { id: 's4_hh_15', description: 'Name the pests and diseases that currently risk entering Ireland and describe how to recognise and deal with them' },
          { id: 's4_hh_16', description: 'Present records of all treatment purchases' },
          { id: 's4_hh_17', description: 'Present records of all treatments applied to colonies' },
          { id: 's4_hh_18', description: 'Discuss how out-of-date or left-over treatments are dealt with' },
          { id: 's4_hh_19', description: 'Describe the signs of honeybee poisoning by natural substances and chemicals' },
          { id: 's4_hh_20', description: 'Name the crops most likely to be sprayed causing poisoning of honeybee colonies' },
          { id: 's4_hh_21', description: 'Describe how beekeepers can reduce the problem of chemical poisoning of honeybee colonies' },
          { id: 's4_hh_22', description: 'Describe the actions to take if chemical poisoning is suspected' },
          { id: 's4_hh_23', description: 'Present and discuss Integrated Pest Management plan/s for candidate\u2019s own apiary/ies' },
        ],
      },
    ],
  },
]

/** Get a specific stage by ID */
export function getStage(stageId: string): LogbookStage | undefined {
  return LOGBOOK_STAGES.find(s => s.id === stageId)
}

/** Count total skills in a stage */
export function getTotalSkillCount(stage: LogbookStage): number {
  return stage.categories.reduce((sum, cat) => sum + cat.skills.length, 0)
}
