-- Migration: Notify admins when new user signs up
-- Date: 2024-12-22
--
-- This migration documents the setup needed for the notify-admin-new-user feature.
-- The actual webhook must be configured in the Supabase Dashboard.
--
-- =============================================================================
-- SETUP INSTRUCTIONS:
-- =============================================================================
--
-- 1. Deploy the Edge Function:
--    - Navigate to Supabase Dashboard > Edge Functions
--    - Deploy the function from: supabase/functions/notify-admin-new-user/index.ts
--    - Or run: supabase functions deploy notify-admin-new-user
--
-- 2. Configure Database Webhook in Supabase Dashboard:
--    - Go to Database > Webhooks
--    - Click "Create a new hook"
--    - Configure as follows:
--
--    Name: notify_admin_new_user
--    Table: profiles
--    Events: INSERT (check only INSERT)
--    Type: Supabase Edge Functions
--    Edge Function: notify-admin-new-user
--    HTTP Headers: (none needed, uses service role automatically)
--
-- 3. Test the webhook:
--    - Sign up a new test user
--    - Check admin email inboxes for notification
--    - Check Edge Function logs in Supabase Dashboard for any errors
--
-- =============================================================================
-- ALTERNATIVE: SQL-based trigger (if pg_net extension is available)
-- =============================================================================
-- Uncomment the following if you prefer SQL triggers over Dashboard webhooks:
--
-- Note: This requires pg_net extension and proper configuration of
-- app.settings.supabase_url and app.settings.service_role_key
--
-- CREATE EXTENSION IF NOT EXISTS pg_net WITH SCHEMA extensions;
--
-- CREATE OR REPLACE FUNCTION public.notify_admin_new_user_trigger()
-- RETURNS TRIGGER
-- LANGUAGE plpgsql
-- SECURITY DEFINER
-- AS $$
-- BEGIN
--   PERFORM net.http_post(
--     url := 'https://tbhofdmfzwibysnnssnx.supabase.co/functions/v1/notify-admin-new-user',
--     headers := '{"Content-Type": "application/json"}'::jsonb,
--     body := jsonb_build_object(
--       'type', 'INSERT',
--       'table', 'profiles',
--       'schema', 'public',
--       'record', jsonb_build_object(
--         'id', NEW.id,
--         'email', NEW.email,
--         'first_name', NEW.first_name,
--         'last_name', NEW.last_name,
--         'role', NEW.role,
--         'created_at', NEW.created_at
--       ),
--       'old_record', null
--     )
--   );
--   RETURN NEW;
-- EXCEPTION WHEN OTHERS THEN
--   RAISE WARNING 'Failed to send admin notification: %', SQLERRM;
--   RETURN NEW;
-- END;
-- $$;
--
-- DROP TRIGGER IF EXISTS on_profile_created_notify_admin ON public.profiles;
-- CREATE TRIGGER on_profile_created_notify_admin
--   AFTER INSERT ON public.profiles
--   FOR EACH ROW
--   EXECUTE FUNCTION public.notify_admin_new_user_trigger();

-- This is a documentation-only migration
-- The actual webhook is configured via Supabase Dashboard
SELECT 'notify-admin-new-user webhook setup documented' AS status;
