import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'
import { buildInsertSql, DATABASE_EXPORT_TABLES, sqlIdentifier, sqlValue } from '@/lib/database-export'

const PUBLIC_SCHEMA = 'public'

// Create admin client with service role key to bypass RLS
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
)

interface MetadataColumnRow {
  table_name: string
  column_name: string
  ordinal_position: number | string
  data_type: string
  not_null: boolean | string
  default_expr: string | null
  identity_kind: string | null
  generated_kind: string | null
}

interface MetadataConstraintRow {
  table_name: string
  constraint_name: string
  constraint_type: string
  constraint_def: string
  ref_schema: string | null
  ref_table: string | null
}

interface MetadataIndexRow {
  table_name: string
  index_name: string
  index_def: string
}

interface MetadataSequenceRow {
  sequence_schema: string
  sequence_name: string
  table_name: string
  column_name: string
}

type SqlRow = Record<string, unknown>

function escapeSqlLiteral(value: string): string {
  return value.replace(/'/g, "''")
}

function tableArrayLiteral(tables: readonly string[]): string {
  return `ARRAY[${tables.map(table => `'${escapeSqlLiteral(table)}'`).join(', ')}]::text[]`
}

async function runSafeSelect<T>(query: string): Promise<T[]> {
  const { data, error } = await supabaseAdmin.rpc('execute_safe_query', { query_text: query })

  if (error) {
    throw new Error(`Failed metadata query: ${error.message}`)
  }

  if (!Array.isArray(data)) {
    return []
  }

  return data as T[]
}

function buildCreateExtensionsBlock(): string {
  return `-- Ensure required extensions exist for default expressions\nDO $$\nBEGIN\n  BEGIN\n    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n  EXCEPTION\n    WHEN insufficient_privilege THEN\n      RAISE NOTICE 'Skipping uuid-ossp extension create due to insufficient privileges';\n  END;\n\n  BEGIN\n    CREATE EXTENSION IF NOT EXISTS "pgcrypto";\n  EXCEPTION\n    WHEN insufficient_privilege THEN\n      RAISE NOTICE 'Skipping pgcrypto extension create due to insufficient privileges';\n  END;\nEND $$;\n`
}

function buildCreateTableStatement(table: string, columns: MetadataColumnRow[]): string {
  const columnLines = columns.map(column => {
    const pieces: string[] = [`${sqlIdentifier(column.column_name)} ${column.data_type}`]
    const identityKind = (column.identity_kind || '').trim()
    const generatedKind = (column.generated_kind || '').trim()
    const defaultExpr = column.default_expr?.trim() || null
    const notNull = column.not_null === true || column.not_null === 'true'

    if (generatedKind === 's' && defaultExpr) {
      pieces.push(`GENERATED ALWAYS AS (${defaultExpr}) STORED`)
    } else if (identityKind === 'a') {
      pieces.push('GENERATED ALWAYS AS IDENTITY')
    } else if (identityKind === 'd') {
      pieces.push('GENERATED BY DEFAULT AS IDENTITY')
    } else if (defaultExpr) {
      pieces.push(`DEFAULT ${defaultExpr}`)
    }

    if (notNull) {
      pieces.push('NOT NULL')
    }

    return `  ${pieces.join(' ')}`
  })

  return `CREATE TABLE IF NOT EXISTS ${sqlIdentifier(PUBLIC_SCHEMA)}.${sqlIdentifier(table)} (\n${columnLines.join(',\n')}\n);\n`
}

function buildAddConstraintBlock(
  tableName: string,
  constraintName: string,
  constraintDefinition: string,
  referencedSchema?: string | null,
  referencedTable?: string | null
): string {
  const escapedDefinition = escapeSqlLiteral(constraintDefinition)
  const alterSql = `ALTER TABLE ${sqlIdentifier(PUBLIC_SCHEMA)}.${sqlIdentifier(tableName)} ADD CONSTRAINT ${sqlIdentifier(constraintName)} ${escapedDefinition};`
  const existsSql = `SELECT 1 FROM pg_constraint c JOIN pg_class t ON t.oid = c.conrelid JOIN pg_namespace n ON n.oid = t.relnamespace WHERE n.nspname = '${escapeSqlLiteral(PUBLIC_SCHEMA)}' AND t.relname = '${escapeSqlLiteral(tableName)}' AND c.conname = '${escapeSqlLiteral(constraintName)}'`

  if (referencedSchema && referencedTable) {
    const referencedRelation = `${escapeSqlLiteral(referencedSchema)}.${escapeSqlLiteral(referencedTable)}`
    return `DO $$\nBEGIN\n  IF NOT EXISTS (${existsSql}) THEN\n    IF to_regclass('${referencedRelation}') IS NULL THEN\n      RAISE NOTICE 'Skipping FK ${escapeSqlLiteral(constraintName)} because ${referencedSchema}.${referencedTable} is unavailable';\n    ELSE\n      EXECUTE '${alterSql}';\n    END IF;\n  END IF;\nEND $$;\n`
  }

  return `DO $$\nBEGIN\n  IF NOT EXISTS (${existsSql}) THEN\n    EXECUTE '${alterSql}';\n  END IF;\nEND $$;\n`
}

function buildCreateIndexStatement(indexDef: string): string {
  const trimmed = indexDef.trim().replace(/;$/, '')
  const withIfNotExists = trimmed
    .replace(/^CREATE UNIQUE INDEX /i, 'CREATE UNIQUE INDEX IF NOT EXISTS ')
    .replace(/^CREATE INDEX /i, 'CREATE INDEX IF NOT EXISTS ')

  return `${withIfNotExists};\n`
}

function buildSequenceResetStatement(sequence: MetadataSequenceRow): string {
  return `SELECT setval('${escapeSqlLiteral(`${sequence.sequence_schema}.${sequence.sequence_name}`)}'::regclass, GREATEST(COALESCE((SELECT MAX(${sqlIdentifier(sequence.column_name)}) FROM ${sqlIdentifier(PUBLIC_SCHEMA)}.${sqlIdentifier(sequence.table_name)}), 0) + 1, 1), false);\n`
}

function buildInsertOnConflictDoNothingSql(
  schema: string,
  table: string,
  row: SqlRow,
  conflictColumns: string[]
): string {
  const columns = Object.keys(row)
  const columnSql = columns.map(sqlIdentifier).join(', ')
  const valuesSql = columns.map(column => sqlValue(row[column])).join(', ')
  const conflictSql = conflictColumns.map(sqlIdentifier).join(', ')

  return `INSERT INTO ${sqlIdentifier(schema)}.${sqlIdentifier(table)} (${columnSql}) VALUES (${valuesSql}) ON CONFLICT (${conflictSql}) DO NOTHING;`
}

function buildTriggerToggleBlock(
  tables: readonly string[],
  action: 'DISABLE' | 'ENABLE'
): string {
  const tableArray = tables.map(table => `'${table}'`).join(', ')

  return `DO $$\nDECLARE\n  table_name text;\nBEGIN\n  FOREACH table_name IN ARRAY ARRAY[${tableArray}]::text[] LOOP\n    BEGIN\n      EXECUTE format('ALTER TABLE public.%I ${action} TRIGGER ALL', table_name);\n    EXCEPTION\n      WHEN insufficient_privilege THEN\n        RAISE NOTICE 'Skipping trigger ${action.toLowerCase()} on %, insufficient privileges', table_name;\n      WHEN undefined_table THEN\n        RAISE NOTICE 'Skipping trigger ${action.toLowerCase()} on %, table not found', table_name;\n    END;\n  END LOOP;\nEND $$;\n`
}

export async function POST(request: NextRequest) {
  try {
    // Verify the requesting user is an admin
    const authHeader = request.headers.get('authorization')
    if (!authHeader) {
      return NextResponse.json(
        { error: 'Missing authorization header' },
        { status: 401 }
      )
    }

    const token = authHeader.replace('Bearer ', '')

    // Verify the token and check user role
    const { data: { user }, error: authError } = await supabaseAdmin.auth.getUser(token)

    if (authError || !user) {
      return NextResponse.json(
        { error: 'Invalid authentication' },
        { status: 401 }
      )
    }

    // Check if user is admin
    const { data: profile, error: profileError } = await supabaseAdmin
      .from('profiles')
      .select('role')
      .eq('id', user.id)
      .single()

    if (profileError || !profile || profile.role !== 'Admin') {
      return NextResponse.json(
        { error: 'Admin access required' },
        { status: 403 }
      )
    }

    console.warn(`[AUDIT] Admin data export: admin=${user.id} status=started timestamp=${new Date().toISOString()}`)

    const tables = [...DATABASE_EXPORT_TABLES]
    const tableArray = tableArrayLiteral(tables)

    const columnMetadata = await runSafeSelect<MetadataColumnRow>(`
      SELECT
        c.relname AS table_name,
        a.attname AS column_name,
        a.attnum AS ordinal_position,
        format_type(a.atttypid, a.atttypmod) AS data_type,
        a.attnotnull AS not_null,
        pg_get_expr(ad.adbin, ad.adrelid) AS default_expr,
        a.attidentity AS identity_kind,
        a.attgenerated AS generated_kind
      FROM pg_class c
      JOIN pg_namespace n ON n.oid = c.relnamespace
      JOIN pg_attribute a ON a.attrelid = c.oid
      LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
      WHERE n.nspname = '${PUBLIC_SCHEMA}'
        AND c.relkind = 'r'
        AND a.attnum > 0
        AND NOT a.attisdropped
        AND c.relname = ANY(${tableArray})
      ORDER BY array_position(${tableArray}, c.relname), a.attnum
    `)

    const constraintMetadata = await runSafeSelect<MetadataConstraintRow>(`
      SELECT
        tbl.relname AS table_name,
        con.conname AS constraint_name,
        con.contype AS constraint_type,
        pg_get_constraintdef(con.oid, true) AS constraint_def,
        ref_ns.nspname AS ref_schema,
        ref_tbl.relname AS ref_table
      FROM pg_constraint con
      JOIN pg_class tbl ON tbl.oid = con.conrelid
      JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
      LEFT JOIN pg_class ref_tbl ON ref_tbl.oid = con.confrelid
      LEFT JOIN pg_namespace ref_ns ON ref_ns.oid = ref_tbl.relnamespace
      WHERE tbl_ns.nspname = '${PUBLIC_SCHEMA}'
        AND tbl.relname = ANY(${tableArray})
        AND con.contype IN ('p', 'u', 'c', 'f', 'x')
      ORDER BY array_position(${tableArray}, tbl.relname), con.contype, con.conname
    `)

    const indexMetadata = await runSafeSelect<MetadataIndexRow>(`
      SELECT
        tbl.relname AS table_name,
        idx.relname AS index_name,
        pg_get_indexdef(idx.oid) AS index_def
      FROM pg_class tbl
      JOIN pg_namespace ns ON ns.oid = tbl.relnamespace
      JOIN pg_index i ON i.indrelid = tbl.oid
      JOIN pg_class idx ON idx.oid = i.indexrelid
      WHERE ns.nspname = '${PUBLIC_SCHEMA}'
        AND tbl.relname = ANY(${tableArray})
        AND NOT i.indisprimary
        AND NOT EXISTS (
          SELECT 1
          FROM pg_constraint c
          WHERE c.conindid = i.indexrelid
        )
      ORDER BY array_position(${tableArray}, tbl.relname), idx.relname
    `)

    const sequenceMetadata = await runSafeSelect<MetadataSequenceRow>(`
      SELECT
        seq_ns.nspname AS sequence_schema,
        seq.relname AS sequence_name,
        tbl.relname AS table_name,
        col.attname AS column_name
      FROM pg_class seq
      JOIN pg_namespace seq_ns ON seq_ns.oid = seq.relnamespace
      JOIN pg_depend dep ON dep.objid = seq.oid AND dep.deptype IN ('a', 'i')
      JOIN pg_class tbl ON tbl.oid = dep.refobjid
      JOIN pg_namespace tbl_ns ON tbl_ns.oid = tbl.relnamespace
      JOIN pg_attribute col ON col.attrelid = tbl.oid AND col.attnum = dep.refobjsubid
      WHERE seq.relkind = 'S'
        AND tbl_ns.nspname = '${PUBLIC_SCHEMA}'
        AND tbl.relname = ANY(${tableArray})
      ORDER BY array_position(${tableArray}, tbl.relname), seq.relname
    `)

    let authUsers: SqlRow[] = []
    let authUsersExportError: string | null = null
    try {
      authUsers = await runSafeSelect<SqlRow>(`
        SELECT *
        FROM auth.users
        ORDER BY created_at NULLS LAST, id
      `)
    } catch (authError) {
      authUsersExportError = authError instanceof Error ? authError.message : 'Unknown auth.users export error'
      console.error('Error exporting auth.users:', authError)
    }

    const columnsByTable = new Map<string, MetadataColumnRow[]>()
    for (const column of columnMetadata) {
      const existing = columnsByTable.get(column.table_name) || []
      existing.push(column)
      columnsByTable.set(column.table_name, existing)
    }

    const nonForeignKeyConstraints = constraintMetadata.filter(constraint => constraint.constraint_type !== 'f')
    const foreignKeyConstraints = constraintMetadata.filter(constraint => constraint.constraint_type === 'f')

    // Build SQL export content
    let sqlContent = `-- =====================================================\n`
    sqlContent += `-- HiveCraic COMPLETE Database Export (ALL USERS)\n`
    sqlContent += `-- Generated on: ${new Date().toISOString()}\n`
    sqlContent += `-- Exported by Admin: ${user.email}\n`
    sqlContent += `-- =====================================================\n\n`
    sqlContent += `-- This export includes ALL data from ALL users\n`
    sqlContent += `-- This export includes schema recreation for public tables, then data\n`
    sqlContent += `-- Auth dependency note: foreign keys to auth.users are emitted with guarded checks\n`
    sqlContent += `-- If auth.users does not exist in target, those FKs are skipped with NOTICE\n\n`

    sqlContent += `-- =====================================================\n`
    sqlContent += `-- SCHEMA RECREATION (PUBLIC)\n`
    sqlContent += `-- =====================================================\n\n`
    sqlContent += `CREATE SCHEMA IF NOT EXISTS ${sqlIdentifier(PUBLIC_SCHEMA)};\n\n`
    sqlContent += buildCreateExtensionsBlock()
    sqlContent += '\n'

    sqlContent += `-- Auth users seed data (for local restore FK compatibility)\n`
    if (authUsersExportError) {
      sqlContent += `-- Skipping auth.users export due to source query error: ${authUsersExportError.replace(/\n/g, ' ')}\n\n`
    } else if (authUsers.length > 0) {
      const authInsertStatements = authUsers.map(userRow =>
        buildInsertOnConflictDoNothingSql('auth', 'users', userRow, ['id'])
      )
      sqlContent += `DO $$\nBEGIN\n  IF to_regclass('auth.users') IS NULL THEN\n    RAISE NOTICE 'Skipping auth.users seed data because auth.users is unavailable in target';\n  ELSE\n`
      for (const statement of authInsertStatements) {
        sqlContent += `    EXECUTE '${escapeSqlLiteral(statement)}';\n`
      }
      sqlContent += `  END IF;\nEND $$;\n\n`
    } else {
      sqlContent += `-- No auth.users rows found in source export\n\n`
    }

    if (sequenceMetadata.length > 0) {
      sqlContent += `-- Sequences\n`
      const seenSequences = new Set<string>()
      for (const sequence of sequenceMetadata) {
        const key = `${sequence.sequence_schema}.${sequence.sequence_name}`
        if (seenSequences.has(key)) {
          continue
        }
        seenSequences.add(key)
        sqlContent += `CREATE SEQUENCE IF NOT EXISTS ${sqlIdentifier(sequence.sequence_schema)}.${sqlIdentifier(sequence.sequence_name)};\n`
      }
      sqlContent += '\n'
    }

    sqlContent += `-- Tables\n`
    for (const table of tables) {
      const tableColumns = columnsByTable.get(table) || []
      if (tableColumns.length === 0) {
        sqlContent += `-- Skipping ${table}: no column metadata found\n`
        continue
      }

      sqlContent += buildCreateTableStatement(table, tableColumns)
      sqlContent += '\n'
    }

    if (sequenceMetadata.length > 0) {
      sqlContent += `-- Sequence ownership\n`
      const seenOwnership = new Set<string>()
      for (const sequence of sequenceMetadata) {
        const key = `${sequence.sequence_schema}.${sequence.sequence_name}:${sequence.table_name}.${sequence.column_name}`
        if (seenOwnership.has(key)) {
          continue
        }
        seenOwnership.add(key)
        sqlContent += `ALTER SEQUENCE ${sqlIdentifier(sequence.sequence_schema)}.${sqlIdentifier(sequence.sequence_name)} OWNED BY ${sqlIdentifier(PUBLIC_SCHEMA)}.${sqlIdentifier(sequence.table_name)}.${sqlIdentifier(sequence.column_name)};\n`
      }
      sqlContent += '\n'
    }

    if (nonForeignKeyConstraints.length > 0) {
      sqlContent += `-- Non-foreign-key constraints\n`
      for (const constraint of nonForeignKeyConstraints) {
        sqlContent += buildAddConstraintBlock(
          constraint.table_name,
          constraint.constraint_name,
          constraint.constraint_def
        )
      }
      sqlContent += '\n'
    }

    if (indexMetadata.length > 0) {
      sqlContent += `-- Secondary indexes\n`
      for (const index of indexMetadata) {
        sqlContent += buildCreateIndexStatement(index.index_def)
      }
      sqlContent += '\n'
    }

    sqlContent += `-- =====================================================\n`
    sqlContent += `-- DATA EXPORT (PUBLIC)\n`
    sqlContent += `-- =====================================================\n\n`
    sqlContent += `BEGIN;\n\n`
    sqlContent += `-- Best effort: disable triggers so inserts can load regardless of FK ordering\n`
    sqlContent += buildTriggerToggleBlock(tables, 'DISABLE')
    sqlContent += '\n'

    // Export data from each table using service role (bypasses RLS)
    const exportResults: Record<string, number> = {}
    const exportErrors: Record<string, string> = {}

    for (const table of tables) {
      try {
        // Use service role client to bypass RLS and get ALL records
        const { data, error } = await supabaseAdmin
          .from(table)
          .select('*')

        if (error) {
          console.error(`Error fetching ${table}:`, error)
          exportResults[table] = 0
          exportErrors[table] = error.message
          continue
        }

        exportResults[table] = data?.length || 0

        if (data && data.length > 0) {
          sqlContent += `\n-- =====================================================\n`
          sqlContent += `-- Table: ${table}\n`
          sqlContent += `-- Records: ${data.length}\n`
          sqlContent += `-- =====================================================\n\n`

          for (const row of data) {
            sqlContent += `${buildInsertSql(PUBLIC_SCHEMA, table, row as Record<string, unknown>)}\n`
          }

          sqlContent += '\n'
        }
      } catch (tableError) {
        console.error(`Error exporting table ${table}:`, tableError)
        exportResults[table] = 0
        exportErrors[table] = tableError instanceof Error ? tableError.message : 'Unknown export error'
      }
    }

    sqlContent += `\n-- Best effort: re-enable triggers after data load\n`
    sqlContent += buildTriggerToggleBlock(tables, 'ENABLE')
    sqlContent += `\nCOMMIT;\n`

    sqlContent += `\n-- =====================================================\n`
    sqlContent += `-- POST-DATA FOREIGN KEYS\n`
    sqlContent += `-- =====================================================\n`
    for (const constraint of foreignKeyConstraints) {
      const isAuthUsersDependency = constraint.ref_schema === 'auth' && constraint.ref_table === 'users'
      sqlContent += buildAddConstraintBlock(
        constraint.table_name,
        constraint.constraint_name,
        constraint.constraint_def,
        isAuthUsersDependency ? constraint.ref_schema : null,
        isAuthUsersDependency ? constraint.ref_table : null
      )
    }
    sqlContent += '\n'

    if (sequenceMetadata.length > 0) {
      sqlContent += `-- =====================================================\n`
      sqlContent += `-- SEQUENCE ALIGNMENT\n`
      sqlContent += `-- =====================================================\n`
      const seenSequenceResets = new Set<string>()
      for (const sequence of sequenceMetadata) {
        const key = `${sequence.sequence_schema}.${sequence.sequence_name}`
        if (seenSequenceResets.has(key)) {
          continue
        }
        seenSequenceResets.add(key)
        sqlContent += buildSequenceResetStatement(sequence)
      }
      sqlContent += '\n'
    }

    sqlContent += `-- =====================================================\n`
    sqlContent += `-- EXPORT SUMMARY\n`
    sqlContent += `-- =====================================================\n`
    sqlContent += `-- Metadata: columns=${columnMetadata.length}, constraints=${constraintMetadata.length}, indexes=${indexMetadata.length}, sequences=${sequenceMetadata.length}\n`
    sqlContent += `-- auth.users rows exported: ${authUsers.length}\n`
    if (authUsersExportError) {
      sqlContent += `-- auth.users export error: ${authUsersExportError.replace(/\n/g, ' ')}\n`
    }
    sqlContent += `-- Total tables: ${tables.length}\n`
    for (const [table, count] of Object.entries(exportResults)) {
      sqlContent += `-- ${table}: ${count} records\n`
    }
    if (Object.keys(exportErrors).length > 0) {
      sqlContent += `-- -----------------------------------------------------\n`
      sqlContent += `-- TABLES WITH EXPORT ERRORS\n`
      sqlContent += `-- -----------------------------------------------------\n`
      for (const [table, message] of Object.entries(exportErrors)) {
        sqlContent += `-- ${table}: ${message.replace(/\n/g, ' ')}\n`
      }
    }
    sqlContent += `-- =====================================================\n`
    sqlContent += `-- END OF EXPORT\n`
    sqlContent += `-- =====================================================\n`

    console.warn(`[AUDIT] Admin data export: admin=${user.id} tables=${tables.length} status=success timestamp=${new Date().toISOString()}`)

    // Return the SQL content with appropriate headers
    return new NextResponse(sqlContent, {
      status: 200,
      headers: {
        'Content-Type': 'text/plain',
        'Content-Disposition': `attachment; filename="hivecraic-complete-export-${new Date().toISOString().split('T')[0]}.sql"`
      }
    })

  } catch (error) {
    console.error('Error in admin export:', error)
    return NextResponse.json(
      { error: 'Failed to export database', details: error instanceof Error ? error.message : 'Unknown error' },
      { status: 500 }
    )
  }
}
