-- OBSOLETE - DO NOT RUN THIS FILE
-- This file created a standalone column which caused inconsistency issues
--
-- The right_sized_broodbox field should ONLY exist in the configuration JSONB object,
-- NOT as a standalone column on the hives table.
--
-- Instead, run: fix_right_sized_broodbox_consistency.sql
-- That script will:
-- 1. Migrate any data from the column to configuration JSONB
-- 2. Remove the standalone column
-- 3. Ensure all data is properly stored in configuration JSONB only

-- Original (incorrect) migration that was replaced:
-- ALTER TABLE hives
-- ADD COLUMN IF NOT EXISTS right_sized_broodbox BOOLEAN DEFAULT false;
