-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.apiaries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  location text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  city text,
  eircode character varying,
  user_id uuid,
  CONSTRAINT apiaries_pkey PRIMARY KEY (id),
  CONSTRAINT apiaries_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT apiaries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.beekeeping_associations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  jurisdiction text CHECK (jurisdiction = ANY (ARRAY['NI'::text, 'ROI'::text])),
  county_area text,
  affiliation text,
  source text,
  website text,
  email text,
  phone text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT beekeeping_associations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.colonies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  colony_number text NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  origin_type text NOT NULL CHECK (origin_type = ANY (ARRAY['purchased'::text, 'split'::text, 'swarm'::text, 'caught_swarm'::text, 'nuc'::text, 'package'::text, 'combine'::text, 'other'::text])),
  origin_date date NOT NULL,
  parent_colony_id uuid,
  secondary_parent_colony_id uuid,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'deceased'::text, 'swarmed'::text, 'combined'::text, 'sold'::text, 'given_away'::text])),
  status_date date,
  status_reason text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT colonies_pkey PRIMARY KEY (id),
  CONSTRAINT colonies_parent_colony_id_fkey FOREIGN KEY (parent_colony_id) REFERENCES public.colonies(id),
  CONSTRAINT colonies_secondary_parent_colony_id_fkey FOREIGN KEY (secondary_parent_colony_id) REFERENCES public.colonies(id),
  CONSTRAINT colonies_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.colony_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  colony_id uuid NOT NULL,
  user_id uuid NOT NULL,
  from_hive_id uuid,
  to_hive_id uuid,
  movement_date date NOT NULL,
  movement_type text NOT NULL CHECK (movement_type = ANY (ARRAY['full_move'::text, 'split_from'::text, 'split_to'::text, 'combine'::text, 'new_colony'::text, 'removed'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT colony_movements_pkey PRIMARY KEY (id),
  CONSTRAINT colony_movements_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id),
  CONSTRAINT colony_movements_from_hive_id_fkey FOREIGN KEY (from_hive_id) REFERENCES public.hives(id),
  CONSTRAINT colony_movements_to_hive_id_fkey FOREIGN KEY (to_hive_id) REFERENCES public.hives(id),
  CONSTRAINT colony_movements_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.del_user_profiles (
  id uuid NOT NULL,
  role character varying NOT NULL DEFAULT 'User'::character varying CHECK (role::text = ANY (ARRAY['User'::character varying, 'Admin'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  first_name character varying,
  last_name character varying,
  mobile_number character varying,
  CONSTRAINT del_user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.dropdown_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_name character varying NOT NULL,
  category_key character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dropdown_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.dropdown_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid NOT NULL,
  value character varying NOT NULL,
  display_order integer NOT NULL DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dropdown_values_pkey PRIMARY KEY (id),
  CONSTRAINT dropdown_values_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.dropdown_categories(id)
);
CREATE TABLE public.feedings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hive_id uuid NOT NULL,
  feed_date date NOT NULL,
  feed_type text NOT NULL,
  quantity numeric,
  unit text NOT NULL DEFAULT 'kg'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  colony_id uuid,
  CONSTRAINT feedings_pkey PRIMARY KEY (id),
  CONSTRAINT feedings_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT feedings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT feedings_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id)
);
CREATE TABLE public.harvests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hive_id uuid NOT NULL,
  harvest_date date NOT NULL,
  honey_weight numeric,
  wax_weight numeric,
  unit text NOT NULL DEFAULT 'kg'::text,
  frames_harvested integer,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  colony_id uuid,
  CONSTRAINT harvests_pkey PRIMARY KEY (id),
  CONSTRAINT harvests_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT harvests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT harvests_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id)
);
CREATE TABLE public.hives (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  apiary_id uuid,
  hive_number text NOT NULL,
  queen_id uuid,
  status text DEFAULT 'active'::text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  queen_marked boolean DEFAULT false,
  queen_marking_color text,
  queen_mated boolean DEFAULT false,
  queen_clipped boolean DEFAULT false,
  colony_established_date date,
  queen_installed_date date,
  hive_type character varying,
  configuration jsonb,
  order_in_apiary integer,
  row_in_apiary integer,
  order_direction text DEFAULT 'entrances'::text CHECK (order_direction = ANY (ARRAY['entrances'::text, 'backs'::text])),
  colony_id uuid,
  archived_at timestamp with time zone,
  archive_reason_id uuid,
  archive_notes text,
  configuration_changed_at timestamp with time zone,
  configuration_changed_by uuid,
  CONSTRAINT hives_pkey PRIMARY KEY (id),
  CONSTRAINT hives_apiary_id_fkey FOREIGN KEY (apiary_id) REFERENCES public.apiaries(id),
  CONSTRAINT hives_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT hives_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id),
  CONSTRAINT hives_archive_reason_id_fkey FOREIGN KEY (archive_reason_id) REFERENCES public.dropdown_values(id),
  CONSTRAINT hives_configuration_changed_by_fkey FOREIGN KEY (configuration_changed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inspections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  hive_id uuid,
  inspection_date date NOT NULL,
  queen_seen boolean,
  eggs_present boolean,
  brood_pattern_rating integer,
  temperament_rating integer,
  population_strength integer,
  honey_stores text,
  disease_issues text,
  notes text,
  inspected_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  brood_frames integer,
  image_url text,
  weather_temp integer,
  weather_condition character varying,
  weather_humidity integer,
  weather_wind_speed integer,
  inspection_time time without time zone,
  user_id uuid,
  right_sized_frames integer,
  swarming_tendency integer DEFAULT 3,
  calmness integer DEFAULT 3,
  frames_foundation integer DEFAULT 0,
  frames_brood integer DEFAULT 0,
  frames_drawn integer DEFAULT 0,
  honey_supers integer DEFAULT 0,
  drone_frames integer DEFAULT 0,
  store_frames integer DEFAULT 0,
  recapping integer DEFAULT 3,
  vsh integer DEFAULT 3,
  smr integer DEFAULT 3,
  afb_disease integer DEFAULT 0,
  efb_disease integer DEFAULT 0,
  chalkbrood_disease integer DEFAULT 0,
  nosemosis_disease integer DEFAULT 0,
  dwv_disease integer DEFAULT 0,
  iapv_cbpv_disease integer DEFAULT 0,
  weight numeric,
  colony_id uuid,
  drone_brood_present boolean DEFAULT false,
  drones_present integer DEFAULT 0 CHECK (drones_present >= 0 AND drones_present <= 3),
  queen_cups boolean DEFAULT false,
  queen_cups_number integer DEFAULT 0 CHECK (queen_cups_number >= 0),
  queen_cups_removed_all boolean DEFAULT false,
  swarm_cells boolean DEFAULT false,
  swarm_cells_number integer DEFAULT 0 CHECK (swarm_cells_number >= 0),
  swarm_cells_removed_all boolean DEFAULT false,
  supercedure_cells boolean DEFAULT false,
  supercedure_cells_number integer DEFAULT 0 CHECK (supercedure_cells_number >= 0),
  supercedure_cells_removed_all boolean DEFAULT false,
  emergency_cells boolean DEFAULT false,
  emergency_cells_number integer DEFAULT 0 CHECK (emergency_cells_number >= 0),
  emergency_cells_removed_all boolean DEFAULT false,
  removed_cells integer DEFAULT 0 CHECK (removed_cells >= 0),
  remaining_cells integer DEFAULT 0 CHECK (remaining_cells >= 0),
  queen_cells_notes text DEFAULT ''::text,
  CONSTRAINT inspections_pkey PRIMARY KEY (id),
  CONSTRAINT inspections_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT inspections_inspected_by_fkey FOREIGN KEY (inspected_by) REFERENCES public.profiles(id),
  CONSTRAINT inspections_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT inspections_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'User'::text CHECK (role = ANY (ARRAY['User'::text, 'Power User'::text, 'Admin'::text])),
  created_at timestamp with time zone DEFAULT now(),
  first_name text,
  last_name text,
  mobile_number text,
  full_name text DEFAULT 
CASE
    WHEN ((first_name IS NOT NULL) AND (last_name IS NOT NULL)) THEN ((first_name || ' '::text) || last_name)
    WHEN (first_name IS NOT NULL) THEN first_name
    WHEN (last_name IS NOT NULL) THEN last_name
    ELSE NULL::text
END,
  is_active boolean DEFAULT true,
  used_registration_code_id uuid,
  subscription_expires_at timestamp with time zone,
  current_subscription_code_id uuid,
  last_subscription_reminder_sent timestamp with time zone,
  subscription_type text CHECK ((subscription_type = ANY (ARRAY['code'::text, 'credit_card'::text, 'none'::text])) OR subscription_type IS NULL),
  subscription_price numeric,
  is_association_member boolean DEFAULT false,
  association_id uuid,
  stripe_customer_id text,
  deleted_at timestamp with time zone,
  original_email text,
  member_fibka boolean DEFAULT false,
  member_iba boolean DEFAULT false,
  member_nihbs boolean DEFAULT false,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_used_registration_code_id_fkey FOREIGN KEY (used_registration_code_id) REFERENCES public.registration_codes(id),
  CONSTRAINT profiles_current_subscription_code_id_fkey FOREIGN KEY (current_subscription_code_id) REFERENCES public.registration_codes(id),
  CONSTRAINT profiles_association_id_fkey FOREIGN KEY (association_id) REFERENCES public.beekeeping_associations(id)
);
CREATE TABLE public.queens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  queen_number text NOT NULL,
  mother_id uuid,
  father_id uuid,
  birth_date date,
  marking_color text,
  source text,
  subspecies text,
  status text DEFAULT 'active'::text,
  performance_notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  lineage text,
  queen_clipped boolean DEFAULT false,
  user_id uuid,
  mated_at_eircode character varying,
  CONSTRAINT queens_pkey PRIMARY KEY (id),
  CONSTRAINT queens_mother_id_fkey FOREIGN KEY (mother_id) REFERENCES public.queens(id),
  CONSTRAINT queens_father_id_fkey FOREIGN KEY (father_id) REFERENCES public.queens(id),
  CONSTRAINT queens_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT queens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.reactivation_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  original_email text NOT NULL,
  requested_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  processed_at timestamp with time zone,
  processed_by uuid,
  admin_notes text,
  CONSTRAINT reactivation_requests_pkey PRIMARY KEY (id),
  CONSTRAINT reactivation_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT reactivation_requests_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.rearing_batches (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  batch_name text NOT NULL,
  mother_queen_id uuid,
  graft_date date NOT NULL,
  cell_count integer,
  emergence_date date,
  status text DEFAULT 'grafted'::text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  acceptance_check_date date,
  grafts_accepted integer,
  queens_hatched integer,
  queens_mated integer,
  starter_colony_hive_id uuid,
  first_option_to_cage_date date,
  second_option_to_cage_date date,
  enable_browser_notifications boolean DEFAULT false,
  enable_email_digest boolean DEFAULT false,
  CONSTRAINT rearing_batches_pkey PRIMARY KEY (id),
  CONSTRAINT rearing_batches_mother_queen_id_fkey FOREIGN KEY (mother_queen_id) REFERENCES public.queens(id),
  CONSTRAINT rearing_batches_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT rearing_batches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT rearing_batches_starter_colony_hive_id_fkey FOREIGN KEY (starter_colony_hive_id) REFERENCES public.hives(id)
);
CREATE TABLE public.registration_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  description text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean DEFAULT true,
  max_uses integer,
  current_uses integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  subscription_expires_at timestamp with time zone,
  code_type USER-DEFINED NOT NULL DEFAULT 'individual'::subscription_code_type,
  association_id uuid,
  CONSTRAINT registration_codes_pkey PRIMARY KEY (id),
  CONSTRAINT registration_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id),
  CONSTRAINT registration_codes_association_id_fkey FOREIGN KEY (association_id) REFERENCES public.beekeeping_associations(id)
);
CREATE TABLE public.subscription_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  code_id uuid,
  code character varying,
  activated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  subscription_type text,
  price_paid numeric,
  code_expires_at timestamp with time zone,
  payment_method text,
  stripe_payment_intent_id text,
  CONSTRAINT subscription_history_pkey PRIMARY KEY (id),
  CONSTRAINT subscription_history_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT subscription_history_code_id_fkey FOREIGN KEY (code_id) REFERENCES public.registration_codes(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  ticket_type character varying NOT NULL CHECK (ticket_type::text = ANY (ARRAY['problem'::character varying::text, 'suggestion'::character varying::text, 'subscription'::character varying::text])),
  subject character varying NOT NULL,
  description text NOT NULL,
  status character varying NOT NULL DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying]::text[])),
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  admin_notes text,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT support_tickets_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES auth.users(id)
);
CREATE TABLE public.tasks_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title character varying NOT NULL,
  description text,
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['task'::character varying, 'event'::character varying, 'reminder'::character varying]::text[])),
  category character varying CHECK (category::text = ANY (ARRAY['inspection'::character varying, 'treatment'::character varying, 'feeding'::character varying, 'harvest'::character varying, 'queen_rearing'::character varying, 'maintenance'::character varying, 'general'::character varying, 'other'::character varying]::text[])),
  start_date date NOT NULL,
  start_time time without time zone,
  end_date date,
  end_time time without time zone,
  all_day boolean DEFAULT false,
  completed boolean DEFAULT false,
  completed_at timestamp with time zone,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  hive_id uuid,
  apiary_id uuid,
  batch_id uuid,
  is_recurring boolean DEFAULT false,
  recurrence_pattern character varying,
  recurrence_end_date date,
  reminder_enabled boolean DEFAULT false,
  reminder_minutes_before integer DEFAULT 60,
  reminder_sent boolean DEFAULT false,
  google_calendar_event_id character varying,
  google_calendar_synced_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_team_task boolean DEFAULT false,
  CONSTRAINT tasks_events_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT tasks_events_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT tasks_events_apiary_id_fkey FOREIGN KEY (apiary_id) REFERENCES public.apiaries(id),
  CONSTRAINT tasks_events_batch_id_fkey FOREIGN KEY (batch_id) REFERENCES public.rearing_batches(id)
);
CREATE TABLE public.team_apiaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  apiary_id uuid NOT NULL,
  added_at timestamp with time zone DEFAULT now(),
  added_by uuid,
  CONSTRAINT team_apiaries_pkey PRIMARY KEY (id),
  CONSTRAINT team_apiaries_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_apiaries_apiary_id_fkey FOREIGN KEY (apiary_id) REFERENCES public.apiaries(id),
  CONSTRAINT team_apiaries_added_by_fkey FOREIGN KEY (added_by) REFERENCES auth.users(id)
);
CREATE TABLE public.team_invitations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  email character varying NOT NULL,
  invited_by uuid NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'accepted'::character varying, 'declined'::character varying, 'expired'::character varying]::text[])),
  invited_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '7 days'::interval),
  accepted_at timestamp with time zone,
  declined_at timestamp with time zone,
  CONSTRAINT team_invitations_pkey PRIMARY KEY (id),
  CONSTRAINT team_invitations_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_invitations_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES auth.users(id)
);
CREATE TABLE public.team_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role character varying DEFAULT 'member'::character varying CHECK (role::text = ANY (ARRAY['owner'::character varying, 'admin'::character varying, 'member'::character varying]::text[])),
  joined_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT team_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  owner_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id)
);
CREATE TABLE public.varroa_checks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  hive_id uuid NOT NULL,
  check_date date NOT NULL,
  method character varying NOT NULL,
  mites_count integer,
  sample_size integer,
  infestation_rate numeric,
  action_threshold_reached boolean DEFAULT false,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  colony_id uuid,
  CONSTRAINT varroa_checks_pkey PRIMARY KEY (id),
  CONSTRAINT varroa_checks_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT varroa_checks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT varroa_checks_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id)
);
CREATE TABLE public.varroa_treatment_products (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  product_name text NOT NULL,
  active_ingredients text NOT NULL,
  notes text,
  application_method text NOT NULL,
  treatment_duration text NOT NULL,
  temperature_range text NOT NULL,
  honey_flow_restrictions text NOT NULL,
  withdrawal_period_days integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT varroa_treatment_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.varroa_treatments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  hive_id uuid NOT NULL,
  treatment_date date NOT NULL,
  treatment_type text NOT NULL,
  dosage text,
  temperature numeric,
  weather_conditions text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  colony_id uuid,
  CONSTRAINT varroa_treatments_pkey PRIMARY KEY (id),
  CONSTRAINT varroa_treatments_hive_id_fkey FOREIGN KEY (hive_id) REFERENCES public.hives(id),
  CONSTRAINT varroa_treatments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT varroa_treatments_colony_id_fkey FOREIGN KEY (colony_id) REFERENCES public.colonies(id)
);